name: mirror
on: 
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

concurrency: 
  group: mirror
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    container:
      image: docker://manjarolinux/build:latest
    steps:
      - name: check out the repo
        id: checkout_repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: s3 sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '*' --include '*.sig' --include '*.zst' --include '*.gz' --include '*.db' --include '*.files'
        env:
          AWS_S3_BUCKET: 'manjaro-sway-packages'
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_REGION: 'auto'
          SOURCE_DIR: './docs'
          AWS_S3_ENDPOINT: https://cd1e88db5a44de0f45317275cbcef879.r2.cloudflarestorage.com
