name: repo-add
on:
  repository_dispatch:
    types: [package_update]

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - id: wait_for_concurrent
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 300
          poll-interval-seconds: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: wait
    runs-on: ubuntu-latest
    container:
      image: docker://archlinux:base-devel
    steps:
      - 
        id: checkout_repo
        uses: actions/checkout@v2
      -
        id: download_release
        env:
          repo: ${{ github.event.client_payload.repository }}
          version: ${{ github.event.client_payload.version }}
          file: ${{ github.event.client_payload.file_name }}
        run:
          wget -o $FILE https://github.com/$REPO/releases/download/$VERSION/$FILE
      - 
        id: update_repo
        run: | 
          mkdir -p docs/
          repo-add docs/packages.db.tar.gz ${{ github.event.client_payload.file_name }}
          git config --global user.name "Repo Update Bot"
          git config --global user.email "info@manjaro-sway.download"
          git add . 
          git commit -m "chore: update ${{github.event.client_payload.repository }}@${{ github.event.client_payload.version }}"
          git push