name: repo
on:
  repository_dispatch:
    types: [package_update]

env:
  REPO_DIR: /builder/repository

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - id: wait_for_concurrent
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 300
          poll-interval-seconds: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: wait
    runs-on: ubuntu-latest
    container:
      image: docker://manjarosway/manjaro-package:latest
    steps:
      - 
        id: checkout
        uses: actions/checkout@v2
        with:
          path: repo
          lfs: true
      - 
        name: check out build target
        id: checkout_src_pkgbuild
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: package
          repository: ${{ github.event.client_payload.repository }}
          ref:  ${{ github.event.client_payload.sha }}
      - 
        id: prepare
        run: |
          cp -f repo/repo.conf /etc/pacman.d/
          pacman -Syyu --noconfirm
          echo "ARCH=`uname -a | sed -E 's/.+ (.+) .+/\1/'`" >> $GITHUB_ENV
          mkdir -p ${REPO_DIR}/${ARCH}
          sudo chown -R builder .
      -
        id: pkgbuild
        working-directory: package
        run: |
          ls -l
          sudo -u builder makepkg --clean -s --noconfirm
          ls -l *.zst