name: repo
on:
  repository_dispatch:
    types: [package_update]

env:
  REPO_DIR: /builder/repository

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - id: wait_for_concurrent
        uses: softprops/turnstyle@v1
        with:
          continue-after-seconds: 300
          poll-interval-seconds: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: wait
    runs-on: ubuntu-latest
    container:
      image: docker://manjarosway/manjaro-package:latest
    steps:
      - 
        name: check out build target
        id: checkout_src_pkgbuild
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: package
          repository: ${{ github.event.client_payload.repository }}
          ref:  ${{ github.event.client_payload.sha }}
      - 
        id: prepare
        run: |
          pacman -Syyu --noconfirm
          echo "ARCH=`uname -a | sed -E 's/.+ (.+) .+/\1/'`" >> $GITHUB_ENV
          mkdir -p ${REPO_DIR}/${ARCH}
          sudo chown -R builder .
      -
        id: pkgbuild
        working-directory: package
        run: |
          sudo -u builder makepkg --clean -s --noconfirm
      - 
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          path: repo
          lfs: true
      - 
        id: update_repo
        working-directory: repo
        env:
          REPO_DIR: docs/${{ env.ARCH }}
        run: |
          mkdir -p $REPO_DIR
          install -D $GITHUB_WORKSPACE/package/*.pkg.tar.zst $REPO_DIR/
          cp -f index.template.html docs/index.html
          cd $REPO_DIR
          repo-add packages.db.tar.gz $REPO_DIR/*.pkg.tar.zst
          git config --global user.name "Repo Update Bot"
          git config --global user.email "info@manjaro-sway.download"
          git add . 
          git commit -m "chore: update ${{ github.event.client_payload.repository }}"
          git push