name: repo-add
on:
  repository_dispatch:
    types: [package_update]

jobs:
  repo-add:
    runs-on: ubuntu-latest
    container:
      image: docker://manjarolinux/build:latest
    steps:
      - uses: ben-z/gh-action-mutex@v1.0-alpha-6
      - name: check out the repo
        id: checkout_repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: 'main'
      - name: setup
        run: |
          git config --global --add safe.directory /__w/packages/packages
          sudo pacman -Sy --noconfirm --needed github-cli
      - name: check if the repo was allowed to dispatch
        id: grant
        env:
          REPO: ${{ github.event.client_payload.repository }}
        run:
          grep -Fxq "${REPO}" allowed_repos
      - name: download the package to be added to the repo
        id: download_release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release download ${{ github.event.client_payload.version }} --repo ${{ github.event.client_payload.repository }} -D /tmp/
          ls -lh /tmp/*.zst*
      - name: gpg-init
        run: |
          # import signing key (no passphrase)
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY_BASE64 }}" | base64 --decode) | gpg --batch --import
          pacman-key --keyserver keyserver.ubuntu.com --recv-keys ${{ secrets.GPG_KEYID }}
          pacman-key --lsign-key ${{ secrets.GPG_KEYID }}
      - name: update the existing repo with the downloaded package
        id: update_repo
        run: |
          mkdir -p docs/x86_64 docs/aarch64
          git config --global user.name "Repo Update Bot"
          git config --global user.email "info@manjaro-sway.download"

          [[ -e /tmp/*x86_64* ]] && cp -f /tmp/*x86_64* docs/x86_64/
          [[ -e /tmp/*aarch64* ]] && cp -f /tmp/*aarch64* docs/aarch64/

          if [ -n "$(git status --porcelain)" ]; then
            rm -f docs/*/manjaro-sway.db* docs/*/manjaro-sway.files*

            repo-add --sign --new --remove --prevent-downgrade docs/x86_64/manjaro-sway.db.tar.gz docs/x86_64/*.zst 
            repo-add --sign --new --remove --prevent-downgrade docs/aarch64/manjaro-sway.db.tar.gz docs/aarch64/*.zst

            rm -f docs/**/*.old* || echo 'no .old files found'
            git add docs/**/*

            size=$(du -sb docs/x86_64/manjaro-sway.db.tar.gz | awk '{ print $1 }')
            if ((size<100)) ; then
              echo "db is too small";
              exit 1;
            fi

            git commit -m "chore: update ${{ github.event.client_payload.repository }} (${{ github.event.client_payload.version }})"
            git push
          fi
      - uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2
        with:
          event-type: new_release
