name: update db
on: 
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

concurrency: 
  group: repo-update
  cancel-in-progress: false

jobs:
  repo-add:
    runs-on: ubuntu-latest
    container:
      image: docker://manjarolinux/base:latest
    steps:
      - name: check out the repo
        id: checkout_repo
        uses: actions/checkout@v3.0.2
      - name: gpg-init
        run: |
          # import signing key (no passphrase)
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY_BASE64 }}" | base64 --decode) | gpg --batch --import
          pacman-key --keyserver keyserver.ubuntu.com --recv-keys ${{ secrets.GPG_KEYID }}
          pacman-key --lsign-key ${{ secrets.GPG_KEYID }}
      - name: update the repo with all currently present packages
        id: update_repo
        run: |
          mkdir -p docs/x86_64 docs/aarch64
          git config --global user.name "Repo Update Bot"
          git config --global user.email "info@manjaro-sway.download"
          git config pull.ff only

          git pull

          rm -f docs/*/manjaro-sway.db.tar.gz
          
          repo-add --sign --new --remove --prevent-downgrade docs/x86_64/manjaro-sway.db.tar.gz docs/x86_64/*.zst || exit 0
          
          repo-add --sign --new --remove --prevent-downgrade docs/aarch64/manjaro-sway.db.tar.gz docs/aarch64/*.zst || exit 0
          
          rm -f docs/*/*.old docs/*/*.old.sig
          date >docs/_includes/date
          git add docs/*
          
          git commit -m "chore: update pkg databases"
          git push
